# Generated by ./update.sh - do not update manually!
{
  version = "7.64";

  x86_64-linux = {
    url = "https://data.tdx.com.cn/uos/com.tdx.tdxcfv_7.64_amd64.deb";
    hash = "sha256-dXv/5pqE9xR6TvdhnJmCKCP5eXiJSAoIK5tgIj2GrbE=";
  };

  aarch64-linux = {
    url = "https://data.tdx.com.cn/uos/com.tdx.tdxcfv_7.64_arm64.deb";
    hash = "sha256-Qt7reorn91XgoglbA1BoLnHu8b92sFzhRPSOw33y22k=";
  };
}
