#!/usr/bin/env bash
# Auto-updater: checks the official download page for the latest TDX version
# and regenerates sources.nix when an update is found. Meant for CI use.
set -euo pipefail

cd "$(dirname "$0")"

down_url=https://www.tdx.com.cn/products/singledown.html
base_url=https://data.tdx.com.cn/uos
nixfile=sources.nix

current_version=$(sed -nE 's/.*version = "([^"]+)".*/\1/p' "$nixfile" | head -1)

echo "Fetching $down_url ..."
page=$(curl -fsSL --retry 3 --retry-all-errors --max-time 60 "$down_url")

latest=$(printf '%s' "$page" |
  sed -nE 's#.*com\.tdx\.tdxcfv_([0-9.]+)_amd64\.deb.*#\1#p' |
  sort -Vu | tail -1)

if [[ -z "$latest" ]]; then
  echo "Failed to extract the latest version from the download page." >&2
  exit 1
fi

echo "Current: $current_version"
echo "Latest:  $latest"

if [[ "$(printf '%s\n%s\n' "$current_version" "$latest" | sort -V | tail -1)" == "$current_version" ]]; then
  echo "Already up to date ($current_version)."
  exit 0
fi

urls=(
  "$base_url/com.tdx.tdxcfv_${latest}_amd64.deb"
  "$base_url/com.tdx.tdxcfv_${latest}_arm64.deb"
)

tmpout=$(mktemp)
trap 'rm -f "$tmpout"' EXIT

echo "Fetching hashes (amd64 + arm64) ..."
printf '%s\n' "${urls[@]}" | nix run github:z1-0/nix-bulkfetch-url -- --fail-fast --timeout 600 > "$tmpout" || {
  echo "Failed to fetch hashes." >&2
  exit 1
}

mapfile -t hashes < "$tmpout"
if [[ ${#hashes[@]} -ne 2 ]]; then
  echo "Expected 2 hashes, got ${#hashes[@]}." >&2
  exit 1
fi

cat > "$nixfile" <<EOF
# Generated by ./update.sh - do not update manually!
{
  version = "$latest";

  x86_64-linux = {
    url = "${urls[0]}";
    hash = "${hashes[0]}";
  };

  aarch64-linux = {
    url = "${urls[1]}";
    hash = "${hashes[1]}";
  };
}
EOF

echo "Regenerated sources.nix for $latest"